name: CI/CD with Terraform
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
  PUBLIC_SSH_KEY: ${{ secrets.PUBLIC_SSH_KEY }}
  AWS_REGION: eu-west-2

jobs:
  deploy-infra:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="region=${{ env.AWS_REGION }}"
      - working-directory: ./terraform
        name: Terraform Plan
        id: plan
        run: |-
          terraform plan \
            -var "region=${{ env.AWS_REGION }}" \
            -var "public_key=${{ env.PUBLIC_SSH_KEY }}" \
            -var "private_key=${{ env.PRIVATE_SSH_KEY }}" \
            -var "key_name=deployer-key" \
            -out=PLAN
        working-directory: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve PLAN
        working-directory: ./terraform