name: CI/CD with Terraform
on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AWS
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: eu-west-2

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="region=${{ env.AWS_REGION }}"
      - name: Terraform Plan
        id: plan
        run: |-
          terraform plan \
            -var "region=${{ env.AWS_REGION }}" \
            -var "ami=ami-018ff7ece22bf96db" \
            -var "public_key=${{ env.PUBLIC_SSH_KEY }}" \
            -var "private_key=${{ env.PRIVATE_SSH_KEY }}" \
            -var "key_name=deployer-key" \
            -out=PLAN
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve PLAN
